# Generated by Django 2.2.2 on 2019-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagem')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Endereço da Internet')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
            ],
        ),
    ]
